# ______     _                    _     _ 
# | ___ \   | |                  | |   | |
# | |_/ /_ _| |_      _____  _ __| | __| |
# |  __/ _` | \ \ /\ / / _ \| '__| |/ _` |
# | | | (_| | |\ V  V / (_) | |  | | (_| |
# \_|  \__,_|_| \_/\_/ \___/|_|  |_|\__,_|             
                                       

### Server ###
ServerName:                             "<SERVER_NAME>"
ServerDescription:                      "<SERVER_DESCRIPTION>"               
ServerPassword:                         "<SERVER_PASSWORD>"                
AdminPassword:                          "<ADMIN_PASSWORD>"                
ServerPlayerMaxNum:                     16                # 16
CoopPlayerMaxNum:                       4                 # 4
GuildPlayerMaxNum:                      20                # 20
BanListURL:                             ""                # "https: //api.palworldgame.com/api/banlist.txt"

Region:                                 "<REGION>"                
PublicIP:                               "<PUBLIC_IP>"                
PublicPort:                             8211
RCONEnabled:                            false
RCONPort:                               25575             # 25575

### World ###
Difficulty:                             null              # null
DayTimeSpeedRate:                       1.000000          # 1.000000
NightTimeSpeedRate:                     1.000000          # 1.000000
ExpRate:                                1.000000          # 1.000000
EnemyDropItemRate:                      1.000000          # 1.000000
DeathPenalty:                           "All"             # "All"
DropItemMaxNum:                         3000              # 3000
DropItemMaxNum_UNKO:                    100               # 100
BaseCampMaxNum:                         128               # 128
BaseCampWorkerMaxNum:                   15                # 15
DropItemAliveMaxHours:                  1.000000          # 1.000000
AutoResetGuildTimeNoOnlinePlayers:      72.000000         # 72.000000
WorkSpeedRate:                          1.000000          # 1.000000

### Player ###
PlayerDamageRateAttack:                 1.000000          # 1.000000
PlayerDamageRateDefense:                1.000000          # 1.000000
PlayerStomachDecreaceRate:              1.000000          # 1.000000
PlayerStaminaDecreaceRate:              1.000000          # 1.000000
PlayerAutoHPRegeneRate:                 1.000000          # 1.000000
PlayerAutoHpRegeneRateInSleep:          1.000000          # 1.000000

### Pal ###
PalCaptureRate:                         1.000000          # 1.000000
PalSpawnNumRate:                        1.000000          # 1.000000
PalDamageRateAttack:                    1.000000          # 1.000000
PalDamageRateDefense:                   1.000000          # 1.000000
PalStomachDecreaceRate:                 1.000000          # 1.000000
PalStaminaDecreaceRate:                 1.000000          # 1.000000
PalAutoHPRegeneRate:                    1.000000          # 1.000000
PalAutoHpRegeneRateInSleep:             1.000000          # 1.000000
PalEggDefaultHatchingTime:              72.000000         # 72.000000

### Build ###
BuildObjectDamageRate:                  1.000000          # 1.000000
BuildObjectDeteriorationDamageRate:     1.000000          # 1.000000

### Collection ###
CollectionDropRate:                     1.000000          # 1.000000
CollectionObjectHpRate:                 1.000000          # 1.000000
CollectionObjectRespawnSpeedRate:       1.000000          # 1.000000

### Variable ###
bIsMultiplay:                           false             # false
bIsPvP:                                 false             # false
bCanPickupOtherGuildDeathPenaltyDrop:   false             # false
bEnableNonLoginPenalty:                 true              # true
bEnableFastTravel:                      true              # true
bIsStartLocationSelectByMap:            true              # true
bExistPlayerAfterLogout:                false             # false
bEnableDefenseOtherGuildPlayer:         false             # false
bUseAuth:                               true              # true
bEnablePlayerToPlayerDamage:            false             # false
bEnableFriendlyFire:                    false             # false
bEnableInvaderEnemy:                    true              # true
bActiveUNKO:                            false             # false
bEnableAimAssistPad:                    true              # true
bEnableAimAssistKeyboard:               false             # false
bAutoResetGuildNoOnlinePlayers:         false             # false
