services:
   palworld-server:
      build: .
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - MULTITHREADING=true
      volumes:
         - ./palworld:/palworld/
         - ./config.yml:/config.yml